- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Find out playbooks path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
    
    - name: PLAY_DIR
      debug:
        msg: "{{project_dir}}"
    
    - name: Init Terraform
      shell: |
        cd {{ project_dir }};
        pwd;
        ls -l;
        {{binary_dir}}/terraform init; 
      register: t_init
      
    - name: "Display output: init resources"
      debug:
        msg: "{{ t_init.stdout }}"
        
    
    - name: Plan Terraform
      shell: |
        cd {{ project_dir }};
        pwd;
        ls -l;
        {{binary_dir}}/terraform plan;
      register: t_plan
      
    - name: "Display output: plan resources"
      debug:
        msg: "{{ t_plan.stdout }}"

        
        
    - name: Apply Terraform
      shell: |
        cd {{ project_dir }};
        pwd;
        ls -l;
        {{binary_dir}}/terraform apply -auto-approve;
      register: t_apply
      
    - name: "Display output: apply resources"
      debug:
        msg: "{{ t_apply.stdout }}"        
        
    #- name: Execute Terraform Plan
    #  terraform:
    #    binary_path: "{{binary_dir}}"
    #    project_path: "{{project_dir}}"
    #    force_init: yes
    #    state: planned

    #- name: Execute Terraform Apply
    #  terraform:
    #    binary_path: "{{binary_dir}}"
    #    project_path: "{{project_dir}}"
    #    state: present

    #- name: Execute Terraform Destroy
    #  terraform:
    #    binary_path: "{{binary_dir}}"
    #    project_path: "{{project_dir}}"
    #    state: absent
