- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Find out playbooks path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
    
    - name: Execute Terraform Plan
      terraform:
        project_path: "{{playbook_dir}}"
        state: planned

    - name: Execute Terraform Apply
      terraform:
        project_path: "{{playbook_dir}}"
        state: present

    - name: Execute Terraform Destroy
      terraform:
        project_path: "{{playbook_dir}}"
        state: absent
