- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Find out playbooks path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
    
    - name: PLAY_DIR
      debug:
        msg: "{{playbook_dir}}"
    
    #- name: Init Terraform
    #  shell: |
    #    cd {{ playbook_dir }};
    #    pwd;
    #    ls -l;
    #    terraform init
    
    - name: Execute Terraform Plan
      terraform:
        binary_path: "{{binary_dir}}"
        project_path: "{{project_dir}}"
    #    force_init: yes
        state: planned

    - name: Execute Terraform Apply
      terraform:
        binary_path: "{{binary_dir}}"
        project_path: "{{project_dir}}"
        state: present

    - name: Execute Terraform Destroy
      terraform:
        binary_path: "{{binary_dir}}"
        project_path: "{{project_dir}}"
        state: absent
